### ISSUE TITLE
How to add custom algo

### ISSUE THREAD

**Issue by arita37** [AxeldeRomblay/MLBox#57] opened 2017-12-10 10:19 UTC
How we can add custom algo as below:

```
   algo.git(X,y)
    algo.predict(X,y)
```

to MLBox algo ?
Am more interested in feature engineering process.

**Comment by AxeldeRomblay** [comment] 2017-12-11 14:59
Hello ! 
What kind of algo is it ? Classification/regression ? which step ? Could you please tell me more or send me your code...

**Comment by arita37** [comment] 2017-12-11 15:02
Hello,

This is regression using FM.

But, in general how we can customize 
so we can wrap our code into a class than mlbox can understand ?

What it the based template of Mlbox ?







On Dec 11, 2017, at 23:59, Axel <notifications@github.com> wrote:

Hello !
What kind of algo is it ? Classification/regression ? which step ? Could you please tell me more or send me your code...

―

**Comment by AxeldeRomblay** [comment] 2019-06-25 11:58
Hello, thanks for reporting this issue. I will close it since this option will be added in a next release (MLBox 1.0.0 probably)

**Closed by AxeldeRomblay** 2019-06-25 11:58 UTC
