### ISSUE TITLE
Cleaning takes too long time on multi-cores cpu

### ISSUE THREAD

**Issue by a1a2y3** [AxeldeRomblay/MLBox#40] opened 2017-08-27 14:40 UTC
Cleaning takes 276s for house price dataset on intel E5-2683v3
As E5-2683 has more 14cores and 28threads. 
I guess the problem may cause by n-job=-1 in here.
` if (self.verbose):
            print("cleaning data ...")

        df = pd.concat(Parallel(n_jobs=-1)(delayed(convert_list)(df[col]) for col in df.columns),
                       axis=1)

        df = pd.concat(Parallel(n_jobs=-1)(delayed(convert_float_and_dates)(df[col]) for col in df.columns), axis=1) `       
I don't know how to fix it, may be add a n_jobs arguments for class Reader? 
Looking for you response. Thank you.

**Comment by a1a2y3** [comment] 2017-08-27 14:49
Drift_thresholder() has same problem.
It takes 1.38s on kaggle kernel, and176s on my PC with E5-2683v3 cpu.

**Comment by AxeldeRomblay** [comment] 2017-08-28 08:13
Hum... sounds very weird ! Because it takes only 2 sec on my computer (7 cores). Have you tried to set n_jobs = 1 and run again ?

**Comment by a1a2y3** [comment] 2017-08-28 15:35
Thank you for reply.  I think joblib or multiprocessing cause this problem, and trying to solve it. 
I use windows10 + anaconda + python3.6 + vs2015, may have conflict with joblib? 

set n_jobs=1, seems OK

reading csv : train.csv ...
cleaning data ...
CPU time: 0.22528505325317383 seconds

reading csv : test.csv ...
cleaning data ...
CPU time: 0.1932668685913086 seconds

**Comment by a1a2y3** [comment] 2017-08-29 05:43
from  http://pythonhosted.org/joblib/parallel.html#common-usage
I found this "Under Windows, it is important to protect the main loop of code to avoid recursive spawning of subprocesses when using joblib.Parallel."..."No code should run outside of the “if __name__ == ‘__main__’” blocks, only imports and definitions."

Problem solved.

**Comment by AxeldeRomblay** [comment] 2017-08-29 12:40
Yes this is what I was wondering. At the moment, MLBox does not support Windows but soon :) 
Thank you very much for reporting this issue !!

**Comment by DarquesM** [comment] 2017-11-20 21:05
I've got same issue, where should I set n_jobs=1 ?
mlbox.preprocessing.Reader does not have "n_jobs" parameter

**Comment by AxeldeRomblay** [comment] 2017-11-21 09:09
Hello @DarquesM  ! 
The problem is due to windows... At the moment what you can do is to set n_jobs=1 in the source code : 

`        ##############################################################
        #             Cleaning lists, floats and dates
        ##############################################################

        if (self.verbose):
            print("cleaning data ...")

        df = pd.concat(Parallel(n_jobs=-1)(delayed(convert_list)(df[col]) for col in df.columns),
                       axis=1)

        df = pd.concat(Parallel(n_jobs=-1)(delayed(convert_float_and_dates)(df[col]) for col in df.columns),
axis=1)`

Otherwise, I will release soon a new version with reading and cleaning separate classes...

**Comment by AxeldeRomblay** [comment] 2019-06-25 11:59
Hello, thanks for reporting this issue. I will close it since this will be fixed in a next release (MLBox 0.7.1 probably)

**Closed by AxeldeRomblay** 2019-06-25 11:59 UTC
